# -*- coding: utf-8 -*-
"""FINAL_Audio_Attacks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALPsJPlCtm2hsnNNr6tba7UePy4nRqA9

ATTACK #1: HIGH-FREQUENCY INJECTION ATTACK (12KHz-19KHz)
"""

"""
High-Frequency Adversarial Audio Generator (12–19 kHz)
------------------------------------------------------
Generates adversarial audio samples by injecting
near-ultrasonic tones (12–19 kHz) into clean audio files.

Outputs:
    - Adversarial audio samples
    - Spectrogram visualizations
    - Waveform comparison plots
    - Metadata JSON file
"""

# ==========================================================
# 1. SETUP AND IMPORTS
# ==========================================================

from google.colab import drive
import os
import numpy as np
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import json
import warnings
warnings.filterwarnings("ignore")

drive.mount('/content/drive')

# Set working directory
project_path = "/content/drive/My Drive/Adversarial_Audio Attack Project"
os.chdir(project_path)

# Validate clean_audio folder
if not os.path.exists("clean_audio"):
    raise FileNotFoundError("Missing folder: clean_audio/")

clean_files = sorted([
    f for f in os.listdir("clean_audio")
    if f.lower().endswith(('.wav', '.mp3', '.flac', '.ogg'))
])

if len(clean_files) == 0:
    raise ValueError("No audio files found inside clean_audio/")

# ==========================================================
# 2. PARAMETERS
# ==========================================================

OUTPUT_FOLDER = "adversarial_audio_highfreq_12_19kHz"
PLOTS_FOLDER = "plots_12_19kHz"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
os.makedirs(PLOTS_FOLDER, exist_ok=True)

FREQUENCIES = [12000, 15000, 17000, 19000]   # Hz
AMPLITUDES = [0.01, 0.05, 0.1]

# ==========================================================
# 3. HIGH-FREQUENCY INJECTION FUNCTION
# ==========================================================

def inject_high_frequency_tone(audio: np.ndarray,
                               sample_rate: int,
                               frequency: int,
                               amplitude: float) -> np.ndarray:
    """
    Injects a high-frequency sine wave into an audio signal.

    Parameters
    ----------
    audio : np.ndarray
        Clean speech waveform.
    sample_rate : int
        Sampling rate.
    frequency : int
        Tone frequency (12–19 kHz).
    amplitude : float
        Tone amplitude (0.01–0.1).

    Returns
    -------
    np.ndarray
        Modified adversarial waveform.
    """
    duration = len(audio) / sample_rate
    t = np.linspace(0, duration, len(audio))

    sine_wave = amplitude * np.sin(2 * np.pi * frequency * t)
    adversarial = audio + sine_wave

    # Normalize to prevent clipping
    max_val = np.max(np.abs(adversarial))
    if max_val > 1:
        adversarial = adversarial / max_val

    return adversarial

# ==========================================================
# 4. GENERATE ALL ADVERSARIAL SAMPLES
# ==========================================================

adversarial_samples = []

for idx, fname in enumerate(clean_files, 1):
    clean_path = os.path.join("clean_audio", fname)
    clean_audio, sr = librosa.load(clean_path, sr=None)
    base = os.path.splitext(fname)[0]

    print(f"[{idx}/{len(clean_files)}] Processing {fname}")

    for freq in FREQUENCIES:
        for amp in AMPLITUDES:

            adv_audio = inject_high_frequency_tone(
                audio=clean_audio,
                sample_rate=sr,
                frequency=freq,
                amplitude=amp
            )

            output_name = f"{base}_freq{freq}_amp{amp:.3f}.wav"
            output_path = os.path.join(OUTPUT_FOLDER, output_name)

            sf.write(output_path, adv_audio, sr)

            adversarial_samples.append({
                "clean_file": fname,
                "adversarial_file": output_name,
                "frequency": freq,
                "amplitude": amp,
                "sample_rate": sr,
                "duration_sec": len(adv_audio) / sr
            })

print("Adversarial audio generation completed.")

# ==========================================================
# 11. GENERATE SAMPLE SPECTROGRAM VISUALIZATIONS
# ==========================================================

def plot_spectrogram_comparison(clean_audio, adv_audio, sr, freq, amp, save_path):
    """
    Generates a side-by-side spectrogram comparison.
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    clean_spec = librosa.amplitude_to_db(np.abs(librosa.stft(clean_audio)), ref=np.max)
    adv_spec = librosa.amplitude_to_db(np.abs(librosa.stft(adv_audio)), ref=np.max)

    librosa.display.specshow(clean_spec, sr=sr, x_axis="time", y_axis="hz", ax=axes[0])
    axes[0].set_title("Clean Audio Spectrogram")

    librosa.display.specshow(adv_spec, sr=sr, x_axis="time", y_axis="hz", ax=axes[1])
    axes[1].set_title(f"Adversarial Spectrogram ({freq} Hz, amp={amp})")

    axes[1].axhline(freq, color="red", linestyle="--", linewidth=1)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


# Select first audio file for visualization
viz_clean, viz_sr = librosa.load(os.path.join("clean_audio", clean_files[0]), sr=None)

viz_configs = [
    (12000, 0.05),
    (15000, 0.05),
    (17000, 0.05),
    (19000, 0.05),
]

for freq, amp in viz_configs:
    adv = inject_high_frequency_tone(viz_clean, viz_sr, freq, amp)
    save_file = f"spectrogram_{freq}Hz_amp{amp:.2f}.png"
    save_path = os.path.join(PLOTS_FOLDER, save_file)

    plot_spectrogram_comparison(viz_clean, adv, viz_sr, freq, amp, save_path)


print("Spectrogram visualizations saved.")

# ==========================================================
# 13. WAVEFORM COMPARISON PLOTS
# ==========================================================

def plot_waveform_comparison(clean_audio, sr, frequencies, amplitude, save_path):
    """
    Plots clean waveform + multiple adversarial waveforms
    for different injected frequencies.
    """
    fig, axes = plt.subplots(len(frequencies) + 1, 1, figsize=(14, 3 * (len(frequencies) + 1)))

    t = np.linspace(0, len(clean_audio) / sr, len(clean_audio))
    axes[0].plot(t, clean_audio, linewidth=0.5)
    axes[0].set_title("Clean Audio Waveform")
    axes[0].grid(alpha=0.3)

    for i, freq in enumerate(frequencies, start=1):
        adv = inject_high_frequency_tone(clean_audio, sr, freq, amplitude)
        axes[i].plot(t, adv, linewidth=0.5)
        axes[i].set_title(f"Injected: {freq} Hz (amp={amplitude})")
        axes[i].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


waveform_path = os.path.join(PLOTS_FOLDER, "waveform_comparison.png")
plot_waveform_comparison(viz_clean, viz_sr, FREQUENCIES, amplitude=0.05, save_path=waveform_path)

print("Waveform comparison saved.")

# ==========================================================
# 14. SAVE METADATA
# ==========================================================

metadata = {
    "attack_type": "high_frequency_injection",
    "frequency_range_hz": FREQUENCIES,
    "amplitudes": AMPLITUDES,
    "clean_files_count": len(clean_files),
    "total_generated_samples": len(adversarial_samples),
    "output_folder": OUTPUT_FOLDER,
    "plots_folder": PLOTS_FOLDER,
    "samples": adversarial_samples
}

metadata_file = f"{OUTPUT_FOLDER}_metadata.json"
with open(metadata_file, "w") as f:
    json.dump(metadata, f, indent=2)

print("Metadata saved.")

"""ATTACK #2: WHITE NOISE INJECTION ATTACK (AMP 0.005, 0.01, 0.02, 0.05)"""

"""
White-Noise Adversarial Audio Generator
---------------------------------------
Generates adversarial audio by adding Gaussian white noise
at multiple intensity levels. Produces:

    - Adversarial audio files
    - Spectrogram visualization
    - Waveform comparison plots
    - Frequency spectrum plots
    - Metadata JSON
"""

# ==========================================================
# 1. SETUP & IMPORTS
# ==========================================================

from google.colab import drive
import os
import numpy as np
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import json
import warnings
warnings.filterwarnings("ignore")

drive.mount("/content/drive")

project_path = "/content/drive/My Drive/Adversarial_Audio Attack Project"
os.chdir(project_path)

if not os.path.exists("clean_audio"):
    raise FileNotFoundError("Missing folder: clean_audio/")

clean_files = sorted([
    f for f in os.listdir("clean_audio")
    if f.lower().endswith((".wav", ".mp3", ".flac", ".ogg"))
])

if len(clean_files) == 0:
    raise ValueError("No audio files found in clean_audio/")

# ==========================================================
# 2. PARAMETERS
# ==========================================================

OUTPUT_FOLDER = "adversarial_audio_whitenoise"
PLOTS_FOLDER = "plots_whitenoise"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
os.makedirs(PLOTS_FOLDER, exist_ok=True)

NOISE_LEVELS = [0.005, 0.01, 0.02, 0.05]  # Updated levels
TOTAL_CONFIGS = len(NOISE_LEVELS)

# ==========================================================
# 3. WHITE-NOISE INJECTION FUNCTION
# ==========================================================

def inject_white_noise(audio: np.ndarray,
                       noise_level: float) -> np.ndarray:
    """
    Inject Gaussian white noise into a waveform.

    Parameters
    ----------
    audio : np.ndarray
        Clean speech waveform.
    noise_level : float
        Std-dev of Gaussian noise (0.005–0.05).

    Returns
    -------
    np.ndarray
        Noisy adversarial audio.
    """
    noise = np.random.normal(0, noise_level, len(audio))
    noisy = audio + noise

    max_val = np.max(np.abs(noisy))
    if max_val > 1:
        noisy = noisy / max_val

    return noisy

# ==========================================================
# 4. GENERATE ALL ADVERSARIAL AUDIO
# ==========================================================

adversarial_samples = []

for idx, fname in enumerate(clean_files, 1):
    clean_path = os.path.join("clean_audio", fname)
    audio, sr = librosa.load(clean_path, sr=None)
    base = os.path.splitext(fname)[0]

    print(f"[{idx}/{len(clean_files)}] Processing {fname}")

    for level in NOISE_LEVELS:
        noisy = inject_white_noise(audio, level)

        output_name = f"{base}_noise{level:.3f}.wav"
        output_path = os.path.join(OUTPUT_FOLDER, output_name)

        sf.write(output_path, noisy, sr)

        adversarial_samples.append({
            "clean_file": fname,
            "adversarial_file": output_name,
            "noise_level": level,
            "sample_rate": sr,
            "duration_sec": len(noisy) / sr
        })

print("White noise adversarial generation complete.")

# ==========================================================
# 5. SPECTROGRAM VISUALIZATION
# ==========================================================

def plot_spectrogram_comparison(clean, noisy, sr, level, save_path):
    """
    Creates a side-by-side spectrogram
    of clean vs noisy audio.
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    clean_spec = librosa.amplitude_to_db(np.abs(librosa.stft(clean)), ref=np.max)
    noisy_spec = librosa.amplitude_to_db(np.abs(librosa.stft(noisy)), ref=np.max)

    librosa.display.specshow(clean_spec, sr=sr, x_axis="time", y_axis="hz", ax=axes[0])
    axes[0].set_title("Clean Audio")

    librosa.display.specshow(noisy_spec, sr=sr, x_axis="time", y_axis="hz", ax=axes[1])
    axes[1].set_title(f"White Noise (level={level})")

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


# Use first file for visualizations
viz_clean, viz_sr = librosa.load(os.path.join("clean_audio", clean_files[0]), sr=None)

for level in NOISE_LEVELS:
    noisy = inject_white_noise(viz_clean, level)
    save_path = os.path.join(PLOTS_FOLDER, f"spectrogram_noise{level:.3f}.png")
    plot_spectrogram_comparison(viz_clean, noisy, viz_sr, level, save_path)

print("Spectrograms saved.")

# ==========================================================
# 6. WAVEFORM COMPARISON PLOT
# ==========================================================

def plot_waveform_comparison(clean, sr, levels, save_path):
    """
    Plots clean waveform and noisy variants
    for all noise levels.
    """
    fig, axes = plt.subplots(len(levels) + 1, 1, figsize=(14, 3 * (len(levels) + 1)))

    t = np.linspace(0, len(clean) / sr, len(clean))
    axes[0].plot(t, clean, linewidth=0.5)
    axes[0].set_title("Clean Audio")
    axes[0].grid(alpha=0.3)

    for i, level in enumerate(levels, start=1):
        noisy = inject_white_noise(clean, level)
        axes[i].plot(t, noisy, linewidth=0.5)
        axes[i].set_title(f"Noise Level {level}")
        axes[i].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


save_path = os.path.join(PLOTS_FOLDER, "waveform_comparison.png")
plot_waveform_comparison(viz_clean, viz_sr, NOISE_LEVELS, save_path)

print("Waveform comparison saved.")

# ==========================================================
# 7. FREQUENCY SPECTRUM PLOT
# ==========================================================

def plot_frequency_spectrum(clean, sr, levels, save_path):
    """
    Compares FFT magnitude of the clean audio
    and noisy versions across all frequencies.
    """
    fig, ax = plt.subplots(figsize=(14, 6))

    # FFT of clean
    fft_clean = np.fft.fft(clean)
    freqs = np.fft.fftfreq(len(clean), 1 / sr)
    pos = freqs > 0

    ax.plot(freqs[pos], np.abs(fft_clean[pos]),
            label="Clean", linewidth=1.3)

    for lvl in levels:
        noisy = inject_white_noise(clean, lvl)
        fft_noisy = np.fft.fft(noisy)
        ax.plot(freqs[pos], np.abs(fft_noisy[pos]),
                label=f"Noise {lvl}", linewidth=1)

    ax.set_xlim([0, min(8000, sr / 2)])
    ax.set_title("Frequency Spectrum Comparison")
    ax.set_xlabel("Frequency (Hz)")
    ax.set_ylabel("Magnitude")
    ax.grid(alpha=0.3)
    ax.legend()

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


save_path = os.path.join(PLOTS_FOLDER, "frequency_spectrum.png")
plot_frequency_spectrum(viz_clean, viz_sr, NOISE_LEVELS, save_path)

print("Frequency spectrum saved.")

# ==========================================================
# 8. SAVE METADATA
# ==========================================================

metadata = {
    "attack_type": "white_noise",
    "noise_levels": NOISE_LEVELS,
    "total_samples": len(adversarial_samples),
    "clean_file_count": len(clean_files),
    "output_folder": OUTPUT_FOLDER,
    "plots_folder": PLOTS_FOLDER,
    "samples": adversarial_samples
}

with open(f"{OUTPUT_FOLDER}_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

print("Metadata saved.")

# ==========================================================
# END
# ==========================================================

print("\nWhite-noise adversarial generation completed successfully.")

"""ATTACKS COMPARISON"""

# Install required packages
!pip install -q openai-whisper jiwer

print("Whisper and jiwer installed!")

import whisper
from jiwer import wer
import matplotlib.pyplot as plt
import numpy as np
import os
import librosa

print("="*70)
print("CREATING ATTACK COMPARISON CHART")
print("="*70)

# ==========================================================
# 1. LOAD CLEAN AUDIO FILES
# ==========================================================

CLEAN_FOLDER = "clean_audio"

if not os.path.exists(CLEAN_FOLDER):
    raise FileNotFoundError("Missing folder: clean_audio/")

audio_files = sorted([
    os.path.join(CLEAN_FOLDER, f)
    for f in os.listdir(CLEAN_FOLDER)
    if f.lower().endswith((".wav", ".mp3", ".flac", ".ogg"))
])

if len(audio_files) == 0:
    raise ValueError("No clean audio files found in clean_audio/")

# Use the first file for comparison
test_file = audio_files[0]
base_name = os.path.splitext(os.path.basename(test_file))[0]

print(f"\nUsing clean audio file: {base_name}\n")


# ==========================================================
# 2. LOAD WHISPER MODEL
# ==========================================================

print("Loading Whisper model...")
model = whisper.load_model("base")
print("✓ Whisper model loaded!\n")


# ==========================================================
# 3. BASELINE CLEAN TRANSCRIPTION
# ==========================================================

print("[1/3] Getting clean transcription...")
clean_result = model.transcribe(test_file)
clean_text = clean_result["text"]

print(f"✓ Clean transcription: \"{clean_text[:60]}...\"")


# ==========================================================
# 4. HIGH-FREQUENCY ATTACK WER TESTING
# ==========================================================

print("\n[2/3] Testing High-Frequency Attacks...")

HF_FOLDER = "adversarial_audio_highfreq_12_19kHz"

hf_test_configs = [
    (12000, 0.01), (12000, 0.05), (12000, 0.10),
    (15000, 0.01), (15000, 0.05), (15000, 0.10),
    (17000, 0.01), (17000, 0.05), (17000, 0.10),
    (19000, 0.01), (19000, 0.05), (19000, 0.10),
]

hf_results = []

for freq, amp in hf_test_configs:
    adv_file = f"{HF_FOLDER}/{base_name}_freq{freq}_amp{amp:.3f}.wav"

    if os.path.exists(adv_file):
        adv_result = model.transcribe(adv_file)
        hf_wer = wer(clean_text, adv_result["text"])

        hf_results.append({
            "frequency": freq,
            "amplitude": amp,
            "wer": hf_wer
        })

        print(f"  ✓ {freq}Hz, amp={amp:.3f}: WER = {hf_wer*100:.1f}%")
    else:
        print(f"  ⚠️ Missing: {os.path.basename(adv_file)}")


# ==========================================================
# 5. WHITE NOISE ATTACK WER TESTING
# ==========================================================

print("\n[3/3] Testing White Noise Attacks...")

WN_FOLDER = "adversarial_audio_whitenoise"

NOISE_LEVELS = [0.005, 0.01, 0.02, 0.05]

wn_results = []

for nl in NOISE_LEVELS:
    noise_file = f"{WN_FOLDER}/{base_name}_noise{nl:.3f}.wav"

    if os.path.exists(noise_file):
        noise_result = model.transcribe(noise_file)
        wn_wer = wer(clean_text, noise_result["text"])

        wn_results.append({
            "noise_level": nl,
            "wer": wn_wer
        })

        print(f"  ✓ Noise {nl:.3f}: WER = {wn_wer*100:.1f}%")
    else:
        print(f"  ⚠️ Missing: {os.path.basename(noise_file)}")


# ==========================================================
# 6. GENERATE COMPARISON CHART
# ==========================================================

print("\n" + "="*70)
print("GENERATING COMPARISON PLOT")
print("="*70)

os.makedirs("plots_whitenoise", exist_ok=True)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# ---- HIGH FREQUENCY ----
if hf_results:
    hf_labels = [f"{r['frequency']//1000}kHz\n{r['amplitude']:.2f}" for r in hf_results]
    hf_values = [r["wer"] * 100 for r in hf_results]

    ax1.bar(hf_labels, hf_values, color="crimson", edgecolor="black")
    ax1.set_title("High-Frequency Attack Effectiveness", fontsize=14)
    ax1.set_ylabel("WER (%)")
    ax1.grid(axis="y", alpha=0.3)

else:
    ax1.text(0.5, 0.5, "No HF files found", ha="center", va="center")


# ---- WHITE NOISE ----
if wn_results:
    wn_labels = [f"{r['noise_level']:.3f}" for r in wn_results]
    wn_values = [r["wer"] * 100 for r in wn_results]

    ax2.bar(wn_labels, wn_values, color="green", edgecolor="black")
    ax2.set_title("White Noise Attack Effectiveness", fontsize=14)
    ax2.set_ylabel("WER (%)")
    ax2.grid(axis="y", alpha=0.3)

else:
    ax2.text(0.5, 0.5, "No white noise files found", ha="center", va="center")


plt.suptitle("Attack Comparison: High-Frequency vs White Noise", fontsize=16)
plt.tight_layout()

save_path = "plots_whitenoise/combined_attack_comparison.png"
plt.savefig(save_path, dpi=300, bbox_inches="tight")
plt.show()

print(f"\n✓ Saved comparison plot to: {save_path}")


# ==========================================================
# 7. SUMMARY
# ==========================================================

if hf_results and wn_results:
    avg_hf = np.mean([r["wer"] for r in hf_results]) * 100
    avg_wn = np.mean([r["wer"] for r in wn_results]) * 100

    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70)

    print(f"High-Frequency Attack → Avg WER: {avg_hf:.1f}%")
    print(f"White Noise Attack → Avg WER: {avg_wn:.1f}%")

    print("\nMore Effective Attack:", end=" ")
    if avg_wn > avg_hf:
        print(f"White Noise ({avg_wn:.1f}% > {avg_hf:.1f}%)")
    else:
        print(f"High-Frequency ({avg_hf:.1f}% > {avg_wn:.1f}%)")

print("\nComparison Complete.")